"use client";
import { createContext, useState, useEffect } from "react";
import "./globals.css";
import { Inter } from "next/font/google";
import axios from "axios";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const peopleContext = createContext();

export default function RootLayout({ children }) {
  const [data, setData] = useState();

  useEffect(() => {
    axios
      .get(`http://localhost:3000/api/people`)
      .then((data) => setData(data.data));
  }, []);

  return (
    <html lang="en">
      <SessionProvider>
        <peopleContext.Provider value={data}>
          <body className={`${inter.className}`}>{children}</body>
        </peopleContext.Provider>
      </SessionProvider>
    </html>
  );
}
